### ISSUE TITLE
Doesn't seem to work on the new Xamarin version (alpha)

### ISSUE THREAD

**Issue by jsucupira** [nicwise/BTProgressHUD#35]
I am getting the following exception: 
System.MissingMethodException: Method not found: 'Foundation.NSString.StringSize'.

The xamarin version that I am running is the latest that supports Unified API with 64-bit Support for iOS and Mac.

Maybe this is the issue? http://forums.xamarin.com/discussion/29448/alpha-chan-no-longer-building-project-after-switching-to-alpha

**Comment by Sankra** [comment]
I also have this problem. Should be fixed now that Xamarin.iOS v 8.6 has hit the stable channel.

**Comment by Sankra** [comment]
Only a recompilation and reup is needed. @jsucupira if you need this to work now, just remove the component versio, download the BTProgressHUD project and add it your own solution. This fixes the problem.

**Comment by nicwise** [comment]
Thanks folks - it's possible that the version on the component store was out of date. Xamarin have JUST released it (about an hour ago), so maybe up date? If not, I'll fix and get a new build in. @Sankra @jsucupira

**Comment by nicwise** [comment]
Hi, I just tried it with v1.15 on the component store, and it works fine. Try updating the component and yell out if it doesn't work @Sankra @jsucupira

**Comment by jsucupira** [comment]
version 1.15 works great.  Thank you.

**Comment by nicwise** [comment]
Awesome!

**Comment by Sankra** [comment]
Yes, nice work!

**Comment by DanilKurkin** [comment]
@nicwise Just downloaded version 1.15 and added to the project ios-unified dll.

On actual build give me this:
Error	102	The type 'UIKit.UIView' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.	

As per Xamarin the fix is:
"Fix: This usually means the project references a component or NuGet package that has not been built with the Unified API. You should delete and re-add all Components and NuGet packages. If this does not fix the error, the external library may not yet support the Unified API."

This is confusing.

**Comment by DanilKurkin** [comment]
I end up downloading and inporting the project.
That way it works perfectly!

Thanks
